# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [31]:
## Assignment 1
import numpy as np
from numpy.random import default_rng
arr = np.eye(4)
print(arr)
print("===================")

arr = np.diag([1,2,3,4,5])
print(arr)
print("===================")

arr = np.diag([1,2,3,4,5],2)
print(arr)
print("===================")

arr = np.zeros((2,8))
print(arr)
print("===================")

arr = np.ones((2,5))
print(arr)
print("===================")

arr = np.ones((2,5))
print(arr)
print("===================")

default_rng(42).random((2,4))
print("===================")

# Ans 1
arr = np.random.randint(1, 21, size=(5, 5))
arr[:,2]=1
print(arr)
print("===================")

# Ans 2
arr = np.random.randint(1,16,size=(4,4))
print(arr)
print("===================")
np.fill_diagonal(arr, 0)
print(arr)
print("===================")


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
[[0 0 1 0 0 0 0]
 [0 0 0 2 0 0 0]
 [0 0 0 0 3 0 0]
 [0 0 0 0 0 4 0]
 [0 0 0 0 0 0 5]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[ 1  8  1 15 10]
 [16  4  1 18 15]
 [ 4 17  1  2 10]
 [ 3 17  1  2  9]
 [12  2  1 17 18]]
[[14 10 15  2]
 [ 5  4  9  6]
 [ 3  8 13  8]
 [10 14 11  9]]
[[ 0 10 15  2]
 [ 5  0  9  6]
 [ 3  8  0  8]
 [10 14 11  0]]


The `np.vander` function in NumPy generates a **Vandermonde matrix**, which is a matrix in which each row is a geometric progression. The general form for creating a Vandermonde matrix with vector `v` and degree `N` is:

\[
\text{Vandermonde matrix} = 
\begin{pmatrix}
v_0^0 & v_0^1 & \dots & v_0^{N-1} \\
v_1^0 & v_1^1 & \dots & v_1^{N-1} \\
\vdots  & \vdots  & \ddots & \vdots \\
v_{n-1}^0 & v_{n-1}^1 & \dots & v_{n-1}^{N-1}
\end{pmatrix}
\]

Where each element of the matrix is formed by raising the elements of the input vector `v` to successive powers.

Let’s break down the three examples you provided:

### 1. `np.vander(np.linspace(0, 2, 5), 2)`
- `np.linspace(0, 2, 5)` generates a vector of 5 linearly spaced values between 0 and 2:  
  \([0. , 0.5, 1. , 1.5, 2. ]\)
- The second argument, `2`, indicates the degree of the Vandermonde matrix, so we will generate a matrix where each element is raised to powers 0 and 1.

Resulting Vandermonde matrix:
\[
\begin{pmatrix}
0^0 & 0^1 \\
0.5^0 & 0.5^1 \\
1^0 & 1^1 \\
1.5^0 & 1.5^1 \\
2^0 & 2^1
\end{pmatrix}
=
\begin{pmatrix}
1 & 0 \\
1 & 0.5 \\
1 & 1 \\
1 & 1.5 \\
1 & 2
\end{pmatrix}
\]

### 2. `np.vander([1, 2, 3, 4], 2)`
- The input is a simple list `[1, 2, 3, 4]`, which corresponds to the vector \([1, 2, 3, 4]\).
- The degree `2` means that each element of the matrix is raised to powers 0 and 1.

Resulting Vandermonde matrix:
\[
\begin{pmatrix}
1^0 & 1^1 \\
2^0 & 2^1 \\
3^0 & 3^1 \\
4^0 & 4^1
\end{pmatrix}
=
\begin{pmatrix}
1 & 1 \\
1 & 2 \\
1 & 3 \\
1 & 4
\end{pmatrix}
\]

### 3. `np.vander((1, 2, 3, 4), 4)`
- This time, the input is a tuple `(1, 2, 3, 4)`, which is treated the same as a list in this case, resulting in the vector \([1, 2, 3, 4]\).
- The degree `4` indicates that the matrix should contain powers from 0 to 3.

Resulting Vandermonde matrix:
\[
\begin{pmatrix}
1^0 & 1^1 & 1^2 & 1^3 \\
2^0 & 2^1 & 2^2 & 2^3 \\
3^0 & 3^1 & 3^2 & 3^3 \\
4^0 & 4^1 & 4^2 & 4^3
\end{pmatrix}
=
\begin{pmatrix}
1 & 1 & 1 & 1 \\
1 & 2 & 4 & 8 \\
1 & 3 & 9 & 27 \\
1 & 4 & 16 & 64
\end{pmatrix}
\]

### Key points:
- `np.vander(x, N)` creates a matrix where `x` is the input array, and the matrix has `N` columns.
- The matrix is populated with the elements of `x` raised to successive powers from 0 to `N-1`.
- The default behavior is that the powers start from the **highest degree** (from left to right). You can reverse the order of powers by using the `increasing=True` argument, but this isn't the case in the examples you provided.

### Summary of Outputs:
- For `np.vander(np.linspace(0, 2, 5), 2)`, you get a 5x2 matrix where the first column is filled with 1s, and the second column contains the values of the input array.
- For `np.vander([1, 2, 3, 4], 2)`, you get a 4x2 matrix with ones in the first column and the elements of the input array in the second column.
- For `np.vander((1, 2, 3, 4), 4)`, you get a 4x4 matrix where each row contains powers of the input elements up to the 3rd power.

In [ ]:
## Assignment 2

# Ans 1
arr = np.random.randint(1, 36, size=(6,6))
print(arr)
print("===================")
print(arr[2:5, :])
print("===================")
print(arr[:,1:4])
print("===================")

# Ans 2
arr = np.random.randint(1,10, size=(5,5))
print(arr)
print("===================")
border_arr = np.concatenate([
    arr[0],
    arr[:, 4],
    arr[4, ::-1],
    arr[::-1, 0]
])
print(border_arr)


[[22 32 23  9 24 23]
 [ 7  5  5  7 16 29]
 [21 11 31 31 14  6]
 [29  6 30 19  2  1]
 [26  7  9 22 26 32]
 [ 8 22  3 13  3  8]]
[[21 11 31 31 14  6]
 [29  6 30 19  2  1]
 [26  7  9 22 26 32]]
[[32 23  9]
 [ 5  5  7]
 [11 31 31]
 [ 6 30 19]
 [ 7  9 22]
 [22  3 13]]
[[2 4 2 5 6]
 [8 7 4 8 7]
 [9 2 9 7 1]
 [3 6 7 9 6]
 [9 4 4 9 4]]
[2 4 2 5 6 6 7 1 6 4 4 9 4 4 9 9 3 9 8 2]


In [60]:
## Assignment 3

# Ans 1
arr1 = np.random.randint(1,10,size=(3,4))
arr2 = np.random.randint(1,10,size=(3,4))
print(arr1)
print(arr2)
print("===================")
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print("===================")

# Ans 2
arr = np.random.randint(1, 16, size=(4,4))
print(arr)
row_sum = np.sum(arr, axis=1)
print(row_sum)
col_sum = np.sum(arr, axis=0)
print(col_sum)

[[2 7 5 9]
 [1 7 4 1]
 [4 3 8 7]]
[[5 5 4 9]
 [3 2 4 8]
 [9 8 1 7]]
[[ 7 12  9 18]
 [ 4  9  8  9]
 [13 11  9 14]]
[[-3  2  1  0]
 [-2  5  0 -7]
 [-5 -5  7  0]]
[[10 35 20 81]
 [ 3 14 16  8]
 [36 24  8 49]]
[[0.4        1.4        1.25       1.        ]
 [0.33333333 3.5        1.         0.125     ]
 [0.44444444 0.375      8.         1.        ]]
[[14 12 10 14]
 [14  2 15  7]
 [12  6  9 13]
 [12 15  2  8]]
[50 38 40 37]
[52 35 36 42]


In [65]:
## Assignment 4

# Ans 1
arr = np.random.randint(1, 20, size=(5,5))
print(arr)
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

# Ans 2
arr = np.random.randint(1,9, size=(3,3))
print(arr)
mean = np.mean(arr)
std_dev = np.std(arr)
normalize_arr = (arr-mean)/std_dev
print(normalize_arr)

[[12  9 19 12 11]
 [19 11  4 18 13]
 [ 8  4 16  5 19]
 [ 2  9  9 10 10]
 [17 10 15 12 10]]
11.36
11.0
4.740295349448175
22.470399999999998
[[7 6 2]
 [4 4 3]
 [5 5 1]]
[[ 1.61245155  1.05429524 -1.17832998]
 [-0.06201737 -0.06201737 -0.62017367]
 [ 0.49613894  0.49613894 -1.73648628]]


In [70]:
## Assignment 5

# Ans 1
arr = np.random.randint(1,20, size=(3,3))
arr1 = np.random.randint(1,20, size=(3,))
print(arr)
print(arr1)
print(arr+arr1)

# Ans 2
arr = np.random.randint(1,20, size=(4,4))
arr1 = np.random.randint(1,20, size=(4,))
print(arr)
print(arr1)
print(arr-arr1)

[[15 13 14]
 [ 5  2  3]
 [ 1 14 14]]
[19  9 11]
[[34 22 25]
 [24 11 14]
 [20 23 25]]
[[ 4 18 17 15]
 [19 19 18 13]
 [14  1  5 14]
 [18  2 17  9]]
[18  9  5  5]
[[-14   9  12  10]
 [  1  10  13   8]
 [ -4  -8   0   9]
 [  0  -7  12   4]]


In [75]:
## Assignment 6

# Ans 1
arr = np.random.randint(1,20, size=(3,3))
print(arr)
print(np.linalg.det(arr))
print(np.linalg.inv(arr))
print(np.linalg.eigvals(arr))
print("===================")

# Ans 2
arr = np.random.randint(1,20, size=(2,3))
arr1 = np.random.randint(1,20, size=(3,2))
print(arr)
print(arr1)
print(np.dot(arr, arr1))



[[10  1 15]
 [ 4 11  5]
 [10  4 12]]
-288.00000000000006
[[-0.38888889 -0.16666667  0.55555556]
 [-0.00694444  0.10416667 -0.03472222]
 [ 0.32638889  0.10416667 -0.36805556]]
[25.02897028 -1.24812581  9.21915553]
[[14  7 18]
 [12 16  6]]
[[12  1]
 [15  6]
 [ 4 15]]
[[345 326]
 [408 198]]


In [85]:
## Assignment 7

# Ans 1
arr = np.arange(1,10).reshape(3,3)
print(arr)
print("===================")

arr1 = arr.reshape(1,9)
print(arr1)
print("===================")

arr1 = arr.reshape(9,1)
print(arr1)
print("===================")


# Ans 2
arr = np.random.randint(1,20, size=(5,5))
print(arr)
print("===================")
flatten_arr = arr.flatten()
print(flatten_arr)
print("===================")
reshaped_arr = flatten_arr.reshape(5,5)
print(reshaped_arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[ 1 10 10 16 19]
 [14 11 15 16 14]
 [11  8 16  1 15]
 [18 14  9 14 10]
 [ 4  1  6 10  5]]
[ 1 10 10 16 19 14 11 15 16 14 11  8 16  1 15 18 14  9 14 10  4  1  6 10
  5]
[[ 1 10 10 16 19]
 [14 11 15 16 14]
 [11  8 16  1 15]
 [18 14  9 14 10]
 [ 4  1  6 10  5]]


In [93]:
## Assingment 8

# Ans 1
arr = np.random.randint(1,20, size=(5,5))
print(arr)
print(arr[[0,0,4,4],[0,4,0,4]])
print("===================")

# Ans 2
arr = np.random.randint(1,20, size=(4,4))
print(arr)
arr[arr>10]=10
print(arr)

[[ 4 10 15 17  4]
 [11  8 17  4  1]
 [15  5  5  4  1]
 [ 2 19 12  7  6]
 [ 3 13  2  5 11]]
[ 4  4  3 11]
[[16  2 10  4]
 [ 3  3  3  6]
 [11  2 12 19]
 [ 1 10 11 10]]
[[10  2 10  4]
 [ 3  3  3  6]
 [10  2 10 10]
 [ 1 10 10 10]]


In [ ]:
## Assignment 9

# Ans 1
dtype = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]

arr = np.array([('Alice', 25, 55.5), 
                 ('Bob', 30, 70.3), 
                 ('Charlie', 20, 60.1), 
                 ('David', 35, 80.2)],
                dtype=dtype)
print(arr)
sorted_data = np.sort(arr, order='age') # Ascending order
# sorted_data = np.sort(arr, order='age')[::-1] # Descending order
print(sorted_data)
print("===================")

# Ans 2


[('Alice', 25, 55.5) ('Bob', 30, 70.3) ('Charlie', 20, 60.1)
 ('David', 35, 80.2)]
[('Charlie', 20, 60.1) ('Alice', 25, 55.5) ('Bob', 30, 70.3)
 ('David', 35, 80.2)]
