Numpy

In [5]:
import numpy as np

## Create array using numpy
## Create a 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [18]:
arr2 = np.array([1,2,3,4,5,6])
arr2.reshape(1,6) ## 1 row 6 colums
arr2=arr2.reshape(3,2) ## 3 rows 2 columns
arr2.shape

(3, 2)

In [23]:
## 2D array
arr3 = np.array([[1,2,3,4,5],[1,2,3,4,5]]) ## 2 rows and 5 columns
arr3.shape 

(2, 5)

In [27]:
np.arange(0,20)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
np.arange(0,20,2).reshape(5,2) ## Reshape this into 5 rows and 2 columns

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [36]:
np.ones((10,5)) ## make an array 10 rows and 5 columns with 1 value assigned

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
## indentity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])