Numpy

In [5]:
import numpy as np

## Create array using numpy
## Create a 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [18]:
arr2 = np.array([1,2,3,4,5,6])
arr2.reshape(1,6) ## 1 row 6 colums
arr2=arr2.reshape(3,2) ## 3 rows 2 columns
arr2.shape

(3, 2)

In [23]:
## 2D array
arr3 = np.array([[1,2,3,4,5],[1,2,3,4,5]]) ## 2 rows and 5 columns
arr3.shape 

(2, 5)

In [27]:
np.arange(0,20)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
np.arange(0,20,2).reshape(5,2) ## Reshape this into 5 rows and 2 columns

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [36]:
np.ones((10,5)) ## make an array 10 rows and 5 columns with 1 value assigned

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
## indentity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
## Atributes of Numpy Array
arr = np.array([[1,2,3], [4,5,6]])

print("Array:\n", arr)
print("Shape:\n", arr.shape)
print("Number of dimensions:",arr.ndim)
print("Size (number of elements):", arr.size)
print("Data type:",arr.dtype)
print("Item size (in bytes):", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape:
 (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [50]:
## Numpy Vectorized Operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## Element Wise Addition
print("Addition:", arr1+arr2) ## size must need to be same

## Element Wise Substraction 
print("Substraction: ", arr1-arr2)

## Element Wise Multiplication
print("Multipllication: ", arr1*arr2)

## Element Wise Division
print("Division: ", arr1/arr2)

Addition: [11 22 33 44 55]
Substraction:  [ -9 -18 -27 -36 -45]
Multipllication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [58]:
## Universal Function -> Basically means some function that applies to the entire array
arr = np.array([16,3,4,5,6])

## Square Root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## Natural log
print(np.log(arr))

# Calculate logarithm with custom base
log_base_2 = np.log(arr) / np.log(2)
print(log_base_2)


[4.         1.73205081 2.         2.23606798 2.44948974]
[8.88611052e+06 2.00855369e+01 5.45981500e+01 1.48413159e+02
 4.03428793e+02]
[-0.28790332  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[2.77258872 1.09861229 1.38629436 1.60943791 1.79175947]
[4.         1.5849625  2.         2.32192809 2.5849625 ]


In [63]:
## Array Slicing and Indexing

arr  = np.array([[1,2,3,4,5],[6,7,8,9,10], [11,12,13,14,15]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [91]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [92]:
arr[1:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [93]:
arr[0:, :-2]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [95]:
## Modify Array elements
arr[0][0]=100
print(arr)

[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]


In [97]:
arr[2][:]=1
print(arr)

[[100   2   3   4   5]
 [  6   7   8   9  10]
 [  1   1   1   1   1]]


In [122]:
## statistical concepts--Normalization
## to have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5,10])

# Calculate the mean ans standard deviation
mean = np.mean(data)
std_dev = np.std(data)

print(mean, std_dev)

## Normalize the data
nd = (data-mean)/std_dev
print("Normalized data: ",nd)

a = np.std(nd)
print(a)


4.166666666666667 2.91070819942883
Normalized data:  [-1.08793684 -0.74437783 -0.40081883 -0.05725983  0.28629917  2.00409417]
1.0


In [123]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

#Mean
mean = np.mean(data)
print("Mean: ",mean)

#Median
median = np.median(data)
print("Median: ",median)

# Standard Deviation
stv_dev = np.std(data)
print("Standard Deviation: ", stv_dev)

# Variance 
variance = np.var(data)
print("Variance: ", variance)


Mean:  5.5
Median:  5.5
Standard Deviation:  2.8722813232690143
Variance:  8.25


In [127]:
## Logical Operation
data = np.array([1,2,3,4,5,6,70,8,9,10])

data > 5

data[data>5]

data[(data>3) & (data<=6)]

array([4, 5, 6])